### ISSUE TITLE
Connot find module ghost-s3

### ISSUE THREAD

**Issue by voigt** [spanishdict/ghost-s3-compat#9]
Hey,

I got the issue, that it was not able to find the storage module, when I followed your installation steps:

```
ERROR: Cannot find module '/home/cv/nodejs/ghost/content/storage/ghost-s3'

 Error: Cannot find module '/home/cv/nodejs/ghost/content/storage/ghost-s3'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.getStorage (/home/cv/nodejs/ghost/core/server/storage/index.js:19:34)
    at setupMiddleware (/home/cv/nodejs/ghost/core/server/middleware/index.js:124:44)
    at /home/cv/nodejs/ghost/core/server/index.js:130:9
    at tryCatcher (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


ERROR: storage[storageChoice] is not a function

 TypeError: storage[storageChoice] is not a function
    at Object.getStorage (/home/cv/nodejs/ghost/core/server/storage/index.js:25:30)
    at setupMiddleware (/home/cv/nodejs/ghost/core/server/middleware/index.js:124:44)
    at /home/cv/nodejs/ghost/core/server/index.js:130:9
    at tryCatcher (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:606:10)


    at Promise._settlePromises (/home/cv/nodejs/ghost/node_modules/bluebird/js/release/promise.js:685:18)
```

I was able to fix it by doing

```
$ cp -r node_modules/ghost-s3-compat content/storage/ghost-s3
```

instead of

```
$ cp -r node_modules/ghost-s3-compat content/storage/ghost-s3-compat
```

Sorry - I'm a little on the rush, so no further investigation - probably the module name can be defined somewhere (maybe in `config.js` `active: ghost-s3`?).

**Comment by cyberrob-zz** [comment]
This works for me: `ghost-s3` to `ghost-s3-compat`

````javascript
storage = {
      active: 'ghost-s3-compat',
      'ghost-s3-compat': {
        accessKeyId:     process.env.S3_ACCESS_KEY_ID,
        secretAccessKey: process.env.S3_ACCESS_SECRET_KEY,
        bucket:          process.env.S3_BUCKET_NAME,
        region:          process.env.S3_BUCKET_REGION
        //assetHost:       process.env.S3_ASSET_HOST_URL
      }
    }
````

**Comment by etanb** [comment]
Where is this configuration in your app? In the `package.json`? or in a separate file?

**Comment by markstos** [comment]
This looks like a possible user error and no one else has reported the same problem in the last 5 years. I think this issue can be closed.
